% 定义数据
batch_sizes = [16, 32, 64, 96];
accuracy = [0.8469, 0.8593, 0.8519, 0.8321];
f1_scores = [0.8306, 0.8403, 0.8256, 0.8090];

% 创建图形窗口
figure('Color', 'white', 'Position', [100, 100, 900, 600]);

% 绘制双柱状图
bar_width = 0.35;
x_positions = 1:length(batch_sizes);

bar1 = bar(x_positions - bar_width/2, accuracy, bar_width, ...
    'FaceColor', [0.2 0.4 0.8], 'EdgeColor', 'none');
hold on;
bar2 = bar(x_positions + bar_width/2, f1_scores, bar_width, ...
    'FaceColor', [0.8 0.4 0.2], 'EdgeColor', 'none');

% 添加数据标签
for i = 1:length(batch_sizes)
    text(x_positions(i) - bar_width/2, accuracy(i) + 0.002, ...
        sprintf('%.4f', accuracy(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 10, ...
        'FontWeight', 'bold');
    
    text(x_positions(i) + bar_width/2, f1_scores(i) + 0.002, ...
        sprintf('%.4f', f1_scores(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', [0.7 0.2 0]);
end

% 设置图形属性
title('批处理大小对模型性能的影响', 'FontSize', 16, 'FontWeight', 'bold');
xlabel('批处理大小', 'FontSize', 13, 'FontWeight', 'bold');
ylabel('性能指标', 'FontSize', 13, 'FontWeight', 'bold');
set(gca, 'XTick', x_positions, 'XTickLabel', arrayfun(@num2str, batch_sizes, 'UniformOutput', false));
grid on;
box on;

% 设置坐标轴范围
ylim([0.79, 0.87]);
xlim([0.4, length(batch_sizes)+0.6]);

% 添加图例和优化
legend([bar1, bar2], {'准确率', 'F1分数'}, 'Location', 'northeast', 'FontSize', 12);

% 添加性能峰值标记
[max_acc, max_acc_idx] = max(accuracy);
line([x_positions(max_acc_idx)-0.5, x_positions(max_acc_idx)+0.5], ...
    [max_acc, max_acc], 'Color', 'red', 'LineStyle', ':', 'LineWidth', 1.5);
text(x_positions(max_acc_idx), max_acc + 0.005, ...
    sprintf('最佳准确率: %.4f', max_acc), ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [1 1 1 0.7]);

% 添加批处理大小说明
annotation('textbox', [0.15, 0.02, 0.7, 0.05], ...
    'String', '注意：批处理大小=32时达到最佳性能', ...
    'EdgeColor', 'none', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.9 0.9 0.9]);